ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app/', include('myapp.urls', namespace='myapp')),
    path('users/', include('users.urls', namespace='users')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

myapp/urls.py
from django.urls import path
from . import views
from myapp.views import ProductListView, ProductDetailView, DeleteView, PaymentSuccessView, PaymentFailedView

app_name = 'myapp'

urlpatterns = [
    path('', views.index, name='homepage'),
    # path('', ProductListView.as_view(), name='homepage'),
    path('<int:pk>/', ProductDetailView.as_view(), name='detail'),
    path('additem/', views.add_item, name='add_item'),
    path('update/<int:my_id>/', views.update_item, name='update_item'),
    path('delete/<int:my_id>/', DeleteView.as_view(), name='delete_item'),
    path('success/<int:my_id>/', PaymentSuccessView.as_view(), name='success'),
    path('failed/<int:my_id>/', PaymentFailedView.as_view(), name='failed'),
    path('api/checkout-session/<int:id>/', DeleteView.as_view(), name='api_checkout_session'),
]

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LoginView, LogoutView

app_name = 'users'

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", LoginView.as_view(template_name='users/login.html'), name="login"),
    path("logout/", LogoutView.as_view(template_name='users/logout.html'), name="logout"),
    path("profile/", views.profile, name="profile"),
    path("sellerprofile/<int:id>/", views.seller_profile, name="sellerprofile"),
]

myapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    seller = models.ForeignKey(User, on_delete=models.CASCADE, default='1')
    name = models.CharField(max_length=100)
    price = models.IntegerField()
    description = models.CharField(max_length=200, null=True)
    image = models.ImageField(blank=True, upload_to='images')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class OrderDetailModel(models.Model):
    customer_username = models.CharField(max_length=200)
    product = models.ForeignKey(Product, on_delete=models.PROTECT)
    amount = models.IntegerField()
    stripe_payment_intent = models.CharField(max_length=200)
    has_paid = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True)

myapp/views.py
import json
import stripe
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseNotFound, JsonResponse
from django.urls import reverse_lazy, reverse
from .models import Product, OrderDetailModel
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, DeleteView, TemplateView
from django.core.paginator import Paginator
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt


def index(request):
    page_obj = items = Product.objects.all()

    item_name = request.GET.get("search")
    if item_name != "" and item_name is not None:
        page_obj = items.filter(name__icontains=item_name)

    paginator = Paginator(page_obj, 3)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    context = {
        'page_obj': page_obj,
    }
    return render(request, "myapp/index.html", context)


class ProductListView(ListView):
    model = Product
    template_name = "myapp/index.html"
    context_object_name = "items"
    paginate_by = 3


# def indexItem(request, my_id):
#     item = Product.objects.get(id=my_id)
#     context = {"item": item}
#     return render(request, "myapp/detail.html", context=context)



# def index_item(request, my_id):
#     item = Product.objects.get(id=my_id)
#     context = {
#         'title': item.name,
#         'item': item,
#     }
#     return render(request, 'myapp/detail.html', context=context)


class ProductDetailView(DetailView):
    model = Product
    template_name = "myapp/detail.html"
    context_object_name = "item"
    pk_url_kwarg = "pk"

    def get_context_data(self, **kwargs):
        context = super(ProductDetailView, self).get_context_data(**kwargs)
        context["stripe_publishable_key"] = settings.STRIPE_PUBLISHABLE_KEY
        return context


@login_required
def add_item(request):
    """
    Add a new item to the database.

    This function handles the HTTP POST request to add a new item to the database.
    It expects the request to contain the following form fields:
    - name: The name of the item.
    - price: The price of the item.
    - description: The description of the item.
    - upload: The image file of the item.

    If the request method is POST, the function extracts the form data and creates a new
    Product object with the extracted data. The seller of the item is set to the current
    user making the request. The new item is then saved to the database.

    If the request method is not POST, the function does nothing and returns a render
    response to the "myapp/additem.html" template with a title of 'Добавить продукт на сайт'.

    Parameters:
    - request (HttpRequest): The HTTP request object.

    Returns:
    - HttpResponse: The rendered response to the "myapp/additem.html" template.
    """
    if request.method == "POST":
        name = request.POST.get("name")
        price = request.POST.get("price")
        description = request.POST.get("description")
        image = request.FILES["upload"]
        seller = request.user
        item = Product(name=name, price=price, description=description, image=image, seller=seller)
        item.save()

    return render(request, "myapp/additem.html", {'title': 'Add new product'})


@login_required
def update_item(request, my_id):
    """
    Updates an item in the database with the given ID.

    Parameters:
    - request (HttpRequest): The HTTP request object.
    - my_id (int): The ID of the item to be updated.

    Returns:
    - HttpResponse: The rendered response to the "myapp/updateitem.html" template.
    """
    item = Product.objects.get(id=my_id)
    if request.method == "POST":
        item.name = request.POST.get("name")
        item.price = request.POST.get("price")
        item.description = request.POST.get("description")
        item.image = request.FILES.get("upload", item.image)  # второй пункт что будет если элемент пустой
        item.save()

        return redirect('myapp:homepage')

    context = {
        'title': f'Update item {item.name}',
        'item': item,
    }

    return render(request, 'myapp/updateitem.html', context)


# @login_required
# def delete_item(request, my_id):
#     """
#     Deletes an item from the database with the given ID.

#     Parameters:
#     - request (HttpRequest): The HTTP request object.
#     - my_id (int): The ID of the item to be deleted.

#     Returns:
#     - HttpResponseRedirect: A redirect response to the "myapp:homepage" URL.
#     """
#     item = Product.objects.get(id=my_id)
#     if request.method == "POST":
#         item.delete()

#         return redirect('myapp:homepage')

#     context = {
#         'title': f'Delete item {item.name}',
#         'item': item,
#     }

#     return render(request, 'myapp/deleteitem.html', context)


@login_required
class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy('myapp:homepage')


@csrf_exempt
def create_checkout_session(request, id):
    product = get_object_or_404(Product, pk=id)

    stripe.api_key = settings.STRIPE_SECRET_KEY
    checkout_session = stripe.checkout.Session.create(
        payment_method_types=["card"],
        line_items=[
            {
                "price_data": {
                    "currency": "usd",
                    "product_data": {
                        "name": product.name,
                    },
                    "unit_amount": int(product.price * 100),
                },
                "quantity": 1,
            }
        ],
        mode="payment",
        success_url=request.build_absolute_uri(reverse("myapp:success"))
        + "?session_id={CHECKOUT_SESSION_ID}",
        cancel_url=request.build_absolute_uri(reverse("myapp:failed")),
    )

    # OrderDetail.objects.create(
    #     customer_email=email,
    #     product=product, ......
    # )

    order = OrderDetailModel()
    order.product = product
    order.stripe_payment_intent = checkout_session["payment_intent"]
    order.amount = int(product.price * 100)
    order.save()

    # return JsonResponse({'data': checkout_session})
    return JsonResponse({"sessionId": checkout_session.id})

class PaymentSuccessView(TemplateView):
    template_name = "myapp/payment_success.html"

    def get(self, request, *args, **kwargs):
        session_id = request.GET.get("session_id")
        if session_id is None:
            return HttpResponseNotFound()

        stripe.api_key = settings.STRIPE_SECRET_KEY
        session = stripe.checkout.Session.retrieve(session_id)

        order = get_object_or_404(
            OrderDetailModel, stripe_payment_intent=session.payment_intent
        )
        order.has_paid = True
        order.save()
        return render(request, self.template_name)


class PaymentFailedView(TemplateView):
    template_name = "myapp/payment_failed.html"

myapp/templates/myapp/additem.html
{% extends "myapp/base.html" %}

{% block content %}
<div class="ml-[200px]">
    <h1 class="text-2xl m-10 font-bold text-green-600"> Add New Item Below</h1>
    <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8 " method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="mb-4 ">
            <label class="block text-gray-700 text-md font-bold mb-2" for="name">Item Name</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Name..." name="name" id="name">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price">Item Price</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Price..." name="price" id="price">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="description">Item Description</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" type="text" placeholder="Description..." name="description" id="description">
            <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload">
            <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Add Item" value="Add Item">Add Item</button>
        </div>
    </form>
</div>

{% endblock content %}

myapp/templates/myapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    <link rel="stylesheet" href="{% static 'myapp/css/styles.css' %}">
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <nav class='bg-white' style='border-bottom: 1px solid #EBEBEB;'>
        <div class='max-w-6x1 mx-auto px-4'>
            <div class='flex justify-between'>
                <div class='flex space-x-7'>
                    <div>
                        <a href="{% url "myapp:homepage" %}" class='flex items-center px-2 py-4'>
                            <span class='text-gray-700 text-xl font-bold'>LiteShop</span>
                        </a>
                    </div>
                    <div class='items-center flex space-x-1'>
                        <a href="{% url 'myapp:homepage' %}" class='py-4 px-2 text-gray-500 font-semibold'>Home</a>
                        {% if user.is_authenticated %}
                            <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'users:profile' %}">Profile</a>
                            <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'users:logout' %}">Logout</a>
                        {% else %}
                            <a class="py-4 px-2 text-gray-500 font-semibold" href="{% url 'users:login' %}">Login</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </nav>
    {% block content %}
    
    {% endblock content %}
</body>
</html>

myapp/templates/myapp/contacts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
</head>
<body>
    <h1>Contacts page</h1>
</body>
</html>

myapp/templates/myapp/deleteitem.html
{% extends "myapp/base.html" %}

{% block content %}
  <h1 class="text-2xl m-10 font bold">Delete Product</h1>
  <form class="bg-white shadow-md m-10 w-3/5 rounded px-8 pt-6 pb-8 mb-4" method="post">
    {% csrf_token %}
    <div class="mb-4">
        <label class="block text-gray text-sm font mb-2">Are you sure you want to delete this item</label>
        <label class="block text-gray text-sm font mb-2">{{ item.name}}</label>
        <img class="w-40 h-40" src="{{ item.image.url}}" alt="" srcset="">
    </div>
    <input class="bg-red-500 text-white px-5 text-sm py-3" type="submit" value="Confirm">
    <a class="button bg-green-500 text-white text-sm px-5 py-3" href="{% url 'myapp:homepage' %}">Cancel</a>
  </form>
{% endblock content %}

myapp/templates/myapp/detail.html
{% extends "myapp/base.html" %}
{% load humanize %}

<title>{{ title }}</title>

{% block content %}
<div class='flex p-10 w-full h-200'>
    <img class='w-1/3' src="{{ item.image.url }}" alt="phone image">
    <div class='w-2/3 text-xl ml-10 mt-5'>
        <p class='mt-3 font-bold text-5xl'>{{ item.name }}</p>
        <p class='mt-3 text-green-500 font-black text-3xl'>${{ item.price | intcomma }}</p>
        <p class='mt-5 text-gray-600 text-sm'>{{ item.description }}</p>
        <p class='text-gray-400 mb-2'><a href="{% url 'users:sellerprofile' item.seller.id %}">from by {{ item.seller }}</a></p>
        <p class='text-gray-400 mb-2'>{{ item.seller.contact_number }}</p>
        {% if user.is_authenticated %}
        <button class='pt-4 pl-4 pr-4 pb-4 text-sm bg-green-500 text-white mt-[50px]' id='checkout'>Checkout</button>
        <button class='pt-4 pl-4 pr-4 pb-4 text-sm bg-gray-500 text-white mt-[50px]'><a href="{% url 'myapp:update_item' item.id %}">Update item</a></button>
        <button class='pt-4 pl-4 pr-4 pb-4 text-sm bg-red-500 text-white mt-[50px]'><a href="{% url 'myapp:delete_item' item.id %}">Delete item</a></button>
        {% endif %}
    </div>
</div>

<script src='https://js.stripe.com/v3/'></script>
<script type="text/javascript">
    // Create an instance of the Stripe object with your publishable API key
    var stripe = Stripe('{{ stripe_publishable_key }}');
    var checkoutButton = document.getElementById('checkout');

    checkoutButton.addEventListener('click', function () {

        // Create a new Checkout Session using the server-side endpoint you
        // created in step 3.
        fetch("{% url 'myapp:api_checkout_session' id=item.id %}", {
            method: 'POST',
        })
            .then(function (response) {
                return response.json();
            })
            .then(function (session) {
                return stripe.redirectToCheckout({ sessionId: session.sessionId });
            })
            .then(function (result) {
                // If `redirectToCheckout` fails due to a browser or network
                // error, you should display the localized error message to your
                // customer using `error.message`.
                if (result.error) {
                    alert(result.error.message);
                }
            })
            .catch(function (error) {
                console.error('Error:', error);
            });
    });
</script>
{% endblock content %}

myapp/templates/myapp/index.html
{% extends 'myapp/base.html' %}
{% load static %}

{% block content %}
<main class="mt-10 max-w-7xl px-4 sm:mt-12 sm:px-6 md:mt-16 lg:mt-20 lg:px-8 xl:mt-28">
    <div class='sm:text-center lg:text-left'>
        <h1 class='text-7xl font-black text-gray-900 sm:text-7xl md:text-7xl'>
            <span class='block xl:inline'>Exclusive phones</span><br>
            <span class='mt--20'>At great prices</span>
        </h1>
        <p class='mt-5 text-base text-gray-700 w-80'>You can order any phones from the presented ranges and get them to your home due to our fast delivery</p>
        {% if user.is_authenticated %}
        <button class='pt-4 pl-4 pr-4 pb-4 text-sm bg-green-500 text-white mt-[50px]'><a href="{% url 'myapp:add_item' %}">Add item</a></button>
        {% endif %}
    </div>
</main>

<div class="mt-5 p-10 justify-center bg-gray-100">
    <h2>Search</h2>
    <form action="" method="get">
        <input type="text" name="search" id="">
    </form>
</div>

<div class='mt-10 p-6 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-3 xl:grid-col-3 lg:grid-col-3 gap-3'>
    {% for item in page_obj %}
        <a href="{% url 'myapp:detail' item.id %}">
            <div class='pr-4 pt-4 pb-4 pl-4 rounded-2xl overflow-hidden' style='border: 1px solid #EBEBEB;'>
                <img class='rounded w-70 h-80 content-center justify-center' src="{{ item.image.url }}" alt="phone image">
                <div clas='px-6 py-4'>
                    <p class='font-bold text-xl mb-2'>{{ item.name| truncatewords:4 }}</p>
                    <p class='text-gray-400'>{{ item.description|truncatewords:6 }}</p>
                    <p class='font-black text-xl text-green-500 mb-2'>${{ item.price }}</p>
                    <p class='text-gray-400 mb-2'>{{ item.seller }}</p>
                </div>
            </div>
        </a>
    {% endfor %}
</div>
<div>
    <span>
        {% if page_obj.has_previous %}
          <a href="?page=1">First</a>
          <a href="?page={{ page_obj.previous_page_number}}">Previous</a>
        {% endif %}
    </span>
    <span>
        {{ page_obj }}
    </span>

    <span>
        {% if page_obj.has_next %}
          <a href="?page={{ page_obj.next_page_number}}">Next</a>
          <a href="?page={{ page_obj.paginator.num_pages}}">Last</a>
        {% endif %}
    </span>
</div>
{% endblock content %}

myapp/templates/myapp/navbar.html
<nav class='bg-white border-gray-500'>
    <div class='max-w-6x1 mx-auto px-4'>
        <div class='flex justify-between'>
            <div class='flex space-x-7'>
                <div>
                    <a href="#" class='flex items-center px-2 py-4'>
                        <img class='h-8 w-8' href='{% url "myapp:homepage" %}' src="{% static 'myapp/images/logo.svg' %}" alt="logo">
                        <span class='text-gray-500 text-xl font-bold'>LiteShop</span>
                    </a>
                </div>
                <div class='items-center flex space-x-1'>
                    <a href="{% url "myapp:homepage" %}" class='py-4 px-2 text-gray-500 font-semibold border-b-2'>Home</a>
                    <a href="#" class='py-4 px-2 text-gray-500 font-semibold'>About</a>
                    <a href="#" class='py-4 px-2 text-gray-500 font-semibold'>Contacts</a>
                </div>
            </div>
        </div>
    </div>
</nav>

myapp/templates/myapp/payment_failed.html
{% extends "myapp/base.html" %}

{% block content %}
    <p>Payment failed</p>
{% endblock content %}

myapp/templates/myapp/payment_success.html
{% extends "myapp/base.html" %}

{% block content %}
    <p>You have successfully paid</p>
{% endblock content %}

myapp/templates/myapp/product_confirm_delete.html
<form action="" method="post">
    {% csrf_token %}
    <p>Are you sure you want to delete this item? {{ object }}</p>
    <input type="submit" value="Confirm">
</form>

myapp/templates/myapp/updateitem.html
{% extends "myapp/base.html" %}

{% block content %}
<div class="ml-[200px]">
    <h1 class="text-2xl m-10 font-bold text-green-600"> Update Item Below</h1>
    <form class="w-1/3 bg-white shadow-md m-10 px-8 py-8 " method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <div class="mb-4 ">
            <label class="block text-gray-700 text-md font-bold mb-2" for="name">Item Name</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value='{{ item.name }}' type="text" placeholder="Name..." name="name" id="name">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="price">Item Price</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value='{{ item.price }}' type="text" placeholder="Price..." name="price" id="price">
            <label class="block text-gray-700 text-md font-bold mb-2 mt-2" for="description">Item Description</label>
            <input class="shadow appearance-none border rounded py-2 px-3 mr-10 text-gray-700" value='{{ item.description }}' type="text" placeholder="Description..." name="description" id="description">
            <div class='w-40 h-40'>
                <img src="{{ item.image.url }}" alt="item image">
            </div>
            <input class="block mt-4" type="file" accept="image/*" name="upload" id="upload">
            <button class="block bg-green-600 text-white p-3 mt-4" type="submit" name="Update Item" value="Update Item">Update Item</button>
        </div>
    </form>
</div>

{% endblock content %}